// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ydjpvzcjwxkdwghxywec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlkanB2emNqd3hrZHdnaHh5d2VjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2ODc3NjMsImV4cCI6MjA2MzI2Mzc2M30.wdlhjhGaYrJyJOM3UQ_9YlKS0lELY5bvOCreiyPv7oI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);